=== Emate04/GT43W5WebXML/GT43W5_0924/GT43W5_mozi.dtd
<!ELEMENT mozi (film*)>
<!ELEMENT film (rendezo+, szinesz+, iro+)>
<!ATTLIST film 
    id ID #REQUIRED
    mufaj (horror | drama | vigjatek) #REQUIRED>

<!ELEMENT rendezo (segédrendezo*, operatőr*)>
<!ATTLIST rendezo
    id ID #IMPLIED
    nev CDATA #IMPLIED>

<!ELEMENT segédrendezo EMPTY>
<!ATTLIST segédrendezo nev CDATA #REQUIRED>

<!ELEMENT operatőr EMPTY>
<!ATTLIST operatőr nev CDATA #REQUIRED>

<!ELEMENT szinesz (gyerekszinesz* , musicalszinesz* , szinkornszinesz*)>
<!ATTLIST szinesz
    id ID #IMPLIED
    nev CDATA #IMPLIED>

<!ELEMENT gyerekszinesz EMPTY>
<!ELEMENT musicalszinesz EMPTY>
<!ELEMENT szinkornszinesz EMPTY>

<!ELEMENT iro (koiro* , lektor*)>
<!ATTLIST iro 
    id ID #IMPLIED
    nev CDATA #IMPLIED>

<!ELEMENT koiro EMPTY>
<!ATTLIST koiro nev CDATA #REQUIRED>

<!ELEMENT lektor EMPTY>
<!ATTLIST lektor nev CDATA #REQUIRED>

=== Emate04/GT43W5WebXML/GT43W5_0924/GT43W5_mozi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mozi SYSTEM "GT43W5_mozi.dtd">
<mozi>
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex" />
        <szinesz id="u5g_4xm_2jb" nev="Madison_Ivy" />
        <szinesz id="a">
            <gyerekszinesz />
            <musicalszinesz />
            <szinkornszinesz />
        </szinesz>
        <iro id="trv_4xm_2jb" />
    </film>
    <film id="txn_nxm_2jb_2" mufaj="drama">
        <rendezo id="rendezo_1" nev="Papp Laszlo">
            <segédrendezo nev="Kiss_Peter" />
            <operatőr nev="Nagy_Kristof" />
        </rendezo>
        <iro id="iro_1" nev="Vereb_Adam">
            <koiro nev="Nagy_Luca" />
            <lektor nev="Hajdu_Laaszlo" />
        </iro>
    </film>
</mozi>
